import Head from "next/head";
import Link from "next/link";

import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>fam Games</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<div className={styles.title}>
					<h1>fam - Games</h1>
				</div>
				<div className={styles.gamesWrapper}>
					<Link href={"/memory"} className={styles.game}>
						<h2>Memory Game</h2>
					</Link>
					<Link href={"/wordle"} className={styles.game}>
						<h2>Wordle</h2>
					</Link>
					<Link href={"/sudoku"} className={styles.game}>
						<h2>Sudoku</h2>
					</Link>
				</div>
			</main>
		</div>
	);
}
